version: '3.9'

services:
  backend:
    image: ${REGISTRY_HOST}/${REGISTRY_ORG}/biopresence-backend:latest
    container_name: biopresence-backend
    ports:
      - '8080:8080'
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/biopresence?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
      - mqtt

  frontend:
    image: ${REGISTRY_HOST}/${REGISTRY_ORG}/biopresence-frontend:latest
    container_name: biopresence-frontend
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: mysql:8.1
    container_name: biopresence-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: biopresence
    volumes:
      - db-data:/var/lib/mysql
      - ../docker/mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - '3306:3306'

  mqtt:
    image: eclipse-mosquitto:2
    container_name: biopresence-mosquitto
    restart: unless-stopped
    ports:
      - '1884:1883'
      - '9001:9001'
    volumes:
      - ../docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

volumes:
  db-data:
    name: biopresence-db-data
